### PR TITLE
Fix missing directory creation command, in case it doesn't yet exist

### PR DESCRIPTION
**Pull request by yihezkel**

### CODE REVIEW

**Comment by bgavrilMS** [comment]
@Peter ***@***.***> - let's make sure to include this fix in our ext release, even if we need to pause it for a day

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pmaytak** [comment]
> @peter ***@***.***> - let's make sure to include this fix in our ext release, even if we need to pause it for a day Get Outlook for Android<https://aka.ms/AAb9ysg>
> […](#)
> ________________________________ From: Yihezkel Schoenbrun ***@***.***> Sent: Wednesday, August 3, 2022 2:03:44 PM To: AzureAD/microsoft-authentication-extensions-for-dotnet ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [AzureAD/microsoft-authentication-extensions-for-dotnet] Fix missing directory creation command, in case it doesn't yet exist (PR #186) Fixes bug introduced in v2.21.0 via #178<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-extensions-for-dotnet%2Fpull%2F178&data=05%7C01%7CBogdan.Gavril%40microsoft.com%7C17c9fbca772b447b352a08da755098de%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637951286288943881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PHbsfoTX8mUACbKeVDB9D9zq4mvxSQPHLETqwejxJnI%3D&reserved=0> The effect is that Kusto users are getting prompted for every command they execute in Kusto Explorer, because our MSAL persistent user token cache is unavailable. The root cause of this seems to be this bug, that MSAL can't create the required Msal.CrossPlatLock if the directory doesn't already exist. Here's the stacktrace Kusto gets: Could not get access to the shared lock file. System.InvalidOperationException: Could not get access to the shared lock file. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\yihezkel\AppData\Roaming\Kusto\userTokenCache.data.lockfile'. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) at Microsoft.Identity.Client.Extensions.Msal.CrossPlatLock..ctor(String lockfilePath, Int32 lockFileRetryDelay, Int32 lockFileRetryCount) --- End of inner exception stack trace --- at Microsoft.Identity.Client.Extensions.Msal.CrossPlatLock..ctor(String lockfilePath, Int32 lockFileRetryDelay, Int32 lockFileRetryCount) at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateCrossPlatLock(StorageCreationProperties storageCreationProperties) at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.<CreateAsync>d__23.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) — Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-extensions-for-dotnet%2Fpull%2F186%23issuecomment-1203922465&data=05%7C01%7CBogdan.Gavril%40microsoft.com%7C17c9fbca772b447b352a08da755098de%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637951286289100090%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=00jy6HR%2Fv8jTD4xwTkfREQDwntlSF79QBLI3W%2FMjoU4%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC5UN2FRTUYPAZDDMGTJ2K3VXJU3BANCNFSM55OU4YSA&data=05%7C01%7CBogdan.Gavril%40microsoft.com%7C17c9fbca772b447b352a08da755098de%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637951286289100090%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Nii6E0%2F39JAKbQ2ZqSTLVfMJ03PTjnfpRqvO71Dr1l0%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

@bgavrilMS Ack.

**Comment by yihezkel** [comment]
We want to decide whether to downgrade the version of MSAL we're using, or to wait for this fix to be included in a release. Do you have a sense of when the next anticipated release will be?

**Comment by pmaytak** [comment]
> We want to decide whether to downgrade the version of MSAL we're using, or to wait for this fix to be included in a release. Do you have a sense of when the next anticipated release will be?

@yihezkel We're about to start release testing, so planning for release tomorrow.

**Comment by bgavrilMS** [comment]
@yihezkel - I merged this PR https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/commit/96dd5bcd53e9bb96c4aa83f064a704efe387e5ef for the issue you raised. It is basically your fix but I added a regression test. Hope you don't mind. 

We are aiming to release today.

**Comment by pmaytak** [comment]
@yihezkel [2.23.0](https://www.nuget.org/packages/Microsoft.Identity.Client.Extensions.Msal/2.23.0) is released.

**Pull request closed without merging**
