### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bgavrilMS**

### CODE REVIEW

**Comment by bgavrilMS** [comment]
I propose to merge this after an MSAL release.

**Review by pmaytak — APPROVED** [review]
What's the leftover work? Archive repo, transfer issues? Can we somehow add a note to the Nuget package also, saying that 4.x is just version sync with MSAL?

Aside: Msal.Extensions.Msal sounds a bit redundant. :)

**Comment by localden** [comment]
How about this @bgavrilMS? (feel free to copy the raw markdown from the comment since I can't suggest more than one line at a time):

>**Note**
>This package continues to be maintained alongside [Microsoft.Identity.Client](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) repository. [Microsoft.Identity.Client.Extensions.Msal](https://www.nuget.org/packages/Microsoft.Identity.Client.Extensions.Msal) will be versioned in sync with [Microsoft.Identity.Client](https://www.nuget.org/packages/Microsoft.Identity.Client). No breaking changes exist between version 2.x and version 4.x

**Comment by pmaytak** [comment]
> How about this @bgavrilMS? (feel free to copy the raw markdown from the comment since I can't suggest more than one line at a time) - this adds the note formatting:
> 
> Note This package continues to be maintained alongside [Microsoft.Identity.Client](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) repository. [Microsoft.Identity.Client.Extensions.Msal](https://www.nuget.org/packages/Microsoft.Identity.Client.Extensions.Msal) will be versioned in sync with [Microsoft.Identity.Client](https://www.nuget.org/packages/Microsoft.Identity.Client). No breaking changes exist between version 2.x and version 4.x

Missing period at the end there.😉

**Review by localden — APPROVED** [review]

**Pull request merged**
