### PR TITLE
Fix for #61 - ignore CacheChange event on Xamarin Mac

### PR DESCRIPTION
**Pull request by bgavrilMS**
fix for #61

### CODE REVIEW

**Comment by tipa** [comment]
Awesome, thanks for the fix - looking forward to the release on NuGet :)

**Comment by bgavrilMS** [comment]
Thanks @tipa, I just need to test it first to avoid embarrassment :)

**Comment by tipa** [comment]
Sure.. I am using the library with the line commented out (instead of catching the exception) without any problems for around 2 months already if that helps your confidence releasing the update :)

**Comment by bgavrilMS** [comment]
It does, I'll cut a release now.

**Pull request merged**
